from .file_operation import read_json, write_json
from .record_operation import student_new_record, teacher_new_record, update_delete_records, menu_update_delete, menu_search_student_teacher, student_object_to_dict, teacher_object_to_dict
